# Generated by Django 5.0.7 on 2024-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_telegram_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
